version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: eisenhower-matrix:latest
    volumes:
      - .env:/app/.env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
#       - DATABASE_URL=your_database_url
#       - API_KEY=your_api_key
    restart: always 